specVersion: 0.2.0
name: bridge-confirm-subql
version: 0.0.4
description: Parallel substrate bridge confirmation service
repository: 'https://github.com/parallel-finance/bridge-confirm-subql'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://regnet2-relay-rpc.parallel.fi'
  genesisHash: '0x4d81c697b5559a627e03cd578c2cc0072fab6b58468cca8b2800465cd5d86a26'
dataSources:
  - kind: substrate/Runtime
    startBlock: 204000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: proxy
            method: proxy
            success: true
